# Generated by Django 5.0.6 on 2024-07-26 07:27

import car.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('year', models.PositiveIntegerField(validators=[car.validators.validate_year])),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('color', models.CharField(max_length=50)),
                ('kilometers', models.PositiveIntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('city', models.CharField(max_length=100)),
            ],
        ),
    ]
