# Generated by Django 5.0.6 on 2024-07-28 15:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0003_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='registered_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='car.person'),
            preserve_default=False,
        ),
    ]
