# Generated by Django 5.0.6 on 2024-08-03 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0005_car_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='is_show',
            field=models.BooleanField(default=True),
        ),
    ]
